// Learn more about F# at http://fsharp.org

open System
open System.IO
open Aardvark.Base
open Aardvark.Compiler.DomainTypes

[<EntryPoint>]
let main argv =

    let log (msg : ErrorInfo) =
        let file = Path.GetFileName msg.file
        match msg.severity with
            | Severity.Debug -> Report.Line(3, "[DTC] {0}: {1}", file, msg.message)
            | Severity.Info -> Report.Line("[DTC] {0}: {1}", file, msg.message)
            | Severity.Warning -> Report.Warn("[DTC] {0}: {1}", file, msg.message)
            | Severity.Error -> Report.Error("[DTC] {0}: {1}", file, msg.message)

    let run = 
        Preprocessing.runFileByFile 
            true 
            log
            @"C:\Development\PRo3D\src\PRo3D.Viewer\PRo3D.Viewer.fsproj"

            (Set.ofList [
                @"C:\Development\PRo3D\packages\Aardium\lib\netstandard2.0\Aardium.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Application\lib\netstandard2.0\Aardvark.Application.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Application.WinForms\lib\net471\Aardvark.Application.WinForms.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Application.WinForms.GL\lib\net471\Aardvark.Application.WinForms.GL.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Application.WinForms.Vulkan\lib\net471\Aardvark.Application.WinForms.Vulkan.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base\lib\netstandard2.0\Aardvark.Base.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.Essentials\lib\netstandard2.0\Aardvark.Base.Essentials.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.FSharp\lib\netstandard2.0\Aardvark.Base.FSharp.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.Incremental\lib\netstandard2.0\Aardvark.Base.Incremental.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.IO\lib\netstandard2.0\Aardvark.Base.IO.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.Rendering\lib\netstandard2.0\Aardvark.Base.Rendering.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.Runtime\lib\netstandard2.0\Aardvark.Base.Runtime.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.Telemetry\lib\netstandard2.0\Aardvark.Base.Telemetry.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Base.TypeProviders\lib\netstandard2.0\Aardvark.Base.TypeProviders.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Cef.WinForms\lib\net471\Aardvark.Cef.WinForms.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Cef.WinForms\lib\net471\Aardvark.Cef.WinForms.Process.exe"
                @"C:\Development\PRo3D\packages\Aardvark.Compiler.DomainTypes\lib\netstandard2.0\Aardvark.Compiler.DomainTypes.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Fitting.Base\lib\net471\Aardvark.Fitting.Base.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Fitting.Planes\lib\net471\Aardvark.Fitting.Planes.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Geometry.Clustering\lib\netstandard2.0\Aardvark.Geometry.Clustering.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Geometry.Intersection\lib\netstandard2.0\Aardvark.Geometry.Intersection.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Geometry.PointTree\lib\netstandard2.0\Aardvark.Geometry.PointTree.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Geometry.PolyMesh\lib\netstandard2.0\Aardvark.Geometry.PolyMesh.dll"
                @"C:\Development\PRo3D\packages\Aardvark.GPGPU\lib\netstandard2.0\Aardvark.GPGPU.dll"
                @"C:\Development\PRo3D\bin\Debug\Aardvark.Opc.dll"
                @"C:\Development\PRo3D\bin\Debug\Aardvark.Prinziple.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Rendering.GL\lib\netstandard2.0\Aardvark.Rendering.GL.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Rendering.Text\lib\netstandard2.0\Aardvark.Rendering.Text.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Rendering.Vulkan\lib\netstandard2.0\Aardvark.Rendering.Vulkan.dll"
                @"C:\Development\PRo3D\packages\Aardvark.SceneGraph\lib\netstandard2.0\Aardvark.SceneGraph.dll"
                @"C:\Development\PRo3D\packages\Aardvark.Service\lib\netstandard2.0\Aardvark.Service.dll"
                @"C:\Development\PRo3D\packages\Aardvark.UI\lib\netstandard2.0\Aardvark.UI.dll"
                @"C:\Development\PRo3D\packages\Aardvark.UI.Primitives\lib\netstandard2.0\Aardvark.UI.Primitives.dll"
                @"C:\Development\PRo3D\packages\Aardvark.VRVis.Base\lib\netstandard2.0\Aardvark.VRVis.Base.dll"
                @"C:\Development\PRo3D\packages\Aardvark.VRVis.Geometry\lib\netstandard2.0\Aardvark.VRVis.Geometry.dll"
                @"C:\Development\PRo3D\packages\Another.Unofficial.Xilium.CefGlue.UnpackNativeDependencies\lib\net45\CefGlue.UnpackNativeDependencies.dll"
                @"C:\Development\PRo3D\packages\CommonMark.NET\lib\net45\CommonMark.dll"
                @"C:\Development\PRo3D\bin\Debug\CSharpUtils.dll"
                @"C:\Development\PRo3D\packages\DevILSharp\lib\netstandard2.0\DevILSharp.dll"
                @"C:\Development\PRo3D\packages\FShade.Core\lib\netstandard2.0\FShade.Core.dll"
                @"C:\Development\PRo3D\packages\FShade.GLSL\lib\netstandard2.0\FShade.GLSL.dll"
                @"C:\Development\PRo3D\packages\FShade.Imperative\lib\netstandard2.0\FShade.Imperative.dll"
                @"C:\Development\PRo3D\packages\FShade.SpirV\lib\netstandard2.0\FShade.SpirV.dll"
                @"C:\Development\PRo3D\packages\FSharp.Core\lib\net45\FSharp.Core.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers\FSharp.Data.TypeProviders.dll"
                @"C:\Development\PRo3D\packages\FsPickler\lib\net45\FsPickler.dll"
                @"C:\Development\PRo3D\packages\FsPickler.Json\lib\net45\FsPickler.Json.dll"
                @"C:\Development\PRo3D\packages\GLSLangSharp\lib\netstandard2.0\GLSLangSharp.dll"
                @"C:\Development\PRo3D\packages\SharpZipLib\lib\20\ICSharpCode.SharpZipLib.dll"
                @"C:\Development\PRo3D\packages\Unofficial.LibTessDotNet\lib\netstandard2.0\LibTessDotNet.dll"
                @"C:\Development\PRo3D\packages\WindowsAPICodePack-Core\lib\Microsoft.WindowsAPICodePack.dll"
                @"C:\Development\PRo3D\packages\WindowsAPICodePack-Shell\lib\Microsoft.WindowsAPICodePack.Shell.dll"
                @"C:\Development\PRo3D\packages\WindowsAPICodePack-ShellExtensions\lib\Microsoft.WindowsAPICodePack.ShellExtensions.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\mscorlib.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\netfx.force.conflicts.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\netstandard.dll"
                @"C:\Development\PRo3D\packages\Newtonsoft.Json\lib\net45\Newtonsoft.Json.dll"
                @"C:\Development\PRo3D\packages\Aardvark.OpenCvSharp\lib\net40\OpenCvSharp.Blob.dll"
                @"C:\Development\PRo3D\packages\Aardvark.OpenCvSharp\lib\net40\OpenCvSharp.dll"
                @"C:\Development\PRo3D\packages\Aardvark.OpenCvSharp\lib\net40\OpenCvSharp.Extensions.dll"
                @"C:\Development\PRo3D\packages\Aardvark.OpenCvSharp\lib\net40\OpenCvSharp.UserInterface.dll"
                @"C:\Development\PRo3D\packages\Unofficial.OpenTK\lib\netstandard2.0\OpenTK.dll"
                @"C:\Development\PRo3D\packages\Unofficial.OpenTK.GLControl\lib\net471\OpenTK.GLControl.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\PresentationFramework.dll"
                @"C:\Development\PRo3D\packages\SKGL\lib\SKGL.dll"
                @"C:\Development\PRo3D\packages\Suave\lib\net40\Suave.dll"
                @"C:\Development\PRo3D\packages\System.Collections.Immutable\lib\netstandard2.0\System.Collections.Immutable.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Core.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Data.Common.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Data.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Diagnostics.StackTrace.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Diagnostics.Tracing.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Drawing.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Globalization.Extensions.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.IO.Compression.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Net.Http.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Net.Sockets.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Numerics.dll"
                @"C:\Development\PRo3D\packages\System.Reactive\lib\net46\System.Reactive.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Runtime.Serialization.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Runtime.Serialization.Primitives.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Security.Cryptography.Algorithms.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Security.SecureString.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Threading.Overlapped.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Windows.Forms.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Xml.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Xml.Linq.dll"
                @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Xml.XPath.XDocument.dll"
                @"C:\Development\PRo3D\packages\Unofficial.Typography\lib\netstandard2.0\Unofficial.Typography.dll"
                @"C:\Development\PRo3D\packages\Another.Unofficial.Xilium.CefGlue\lib\net40\Xilium.CefGlue.dll"
                @"C:\Development\PRo3D\packages\Another.Unofficial.Xilium.CefGlue.WindowsForms\lib\net40\Xilium.CefGlue.WindowsForms.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\Microsoft.Win32.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.AppContext.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Collections.Concurrent.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Collections.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Collections.NonGeneric.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Collections.Specialized.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ComponentModel.Annotations.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ComponentModel.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ComponentModel.EventBasedAsync.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ComponentModel.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ComponentModel.TypeConverter.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Console.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Diagnostics.Contracts.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Diagnostics.Debug.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Diagnostics.FileVersionInfo.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Diagnostics.Process.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Diagnostics.TextWriterTraceListener.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Diagnostics.Tools.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Diagnostics.TraceSource.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Drawing.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Dynamic.Runtime.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Globalization.Calendars.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Globalization.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.Compression.ZipFile.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.FileSystem.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.FileSystem.DriveInfo.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.FileSystem.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.FileSystem.Watcher.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.IsolatedStorage.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.MemoryMappedFiles.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.Pipes.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.IO.UnmanagedMemoryStream.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Linq.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Linq.Expressions.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Linq.Parallel.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Linq.Queryable.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.Http.Rtc.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.NameResolution.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.NetworkInformation.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.Ping.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.Requests.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.Security.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.WebHeaderCollection.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.WebSockets.Client.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Net.WebSockets.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ObjectModel.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Reflection.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Reflection.Emit.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Reflection.Emit.ILGeneration.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Reflection.Emit.Lightweight.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Reflection.Extensions.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Reflection.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Resources.Reader.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Resources.ResourceManager.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Resources.Writer.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.CompilerServices.VisualC.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.Extensions.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.Handles.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.InteropServices.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.InteropServices.RuntimeInformation.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.InteropServices.WindowsRuntime.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.Numerics.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.Serialization.Formatters.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.Serialization.Json.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Runtime.Serialization.Xml.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Security.Claims.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Security.Cryptography.Csp.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Security.Cryptography.Encoding.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Security.Cryptography.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Security.Cryptography.X509Certificates.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Security.Principal.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ServiceModel.Duplex.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ServiceModel.Http.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ServiceModel.NetTcp.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ServiceModel.Primitives.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ServiceModel.Security.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Text.Encoding.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Text.Encoding.Extensions.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Text.RegularExpressions.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Threading.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Threading.Tasks.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Threading.Tasks.Parallel.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Threading.Thread.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Threading.ThreadPool.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Threading.Timer.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ValueTuple.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Xml.ReaderWriter.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Xml.XDocument.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Xml.XmlDocument.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Xml.XmlSerializer.dll"
                @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.Xml.XPath.dll"
            ])

            [
                @"Config.fs"
                @"Model.fs"
                @"Utilities.fs"
                @"GuiEx.fs"
                @"KdTrees.fs"
                @"ReferenceSystem-Model.fs"
                @"CooTransformation.fs"
                @"DipAndStrike.fs"
                @"ReferenceSystem.fs"
                @"Surface-Model.fs"
                @"Navigation-Model.fs"
                @"Bookmark-Model.fs"
                @"Csv.fs"
                @"GroupsModels.fs"
                @"Groups.fs"
                @"Drawing-Properties.fs"
                @"Drawing\Drawing-Model.fs"
                @"Drawing\Drawing.fs"
                @"MeasurementsImporter.fs"
                @"Navigation.fs"
                @"AlignmentModel.fs"
                @"AlignmentApp.fs"
                @"Surface-Properties.fs"
                @"Surface.fs"
                @"Rover-Model.fs"
                @"Rover.fs"
                @"ViewPlan.fs"
                @"Properties.fs"
                @"ConfigTestModel.fs"
                @"ConfigTest.fs"
                @"Viewer-Model.fs"
                @"Bookmarks.fs"
                @"Scene.fs"
                @"LensConfigs.fs"
                @"AnnotationGroupsImporter.fs"
                @"SurfaceTrafoImporter.fs"
                @"Viewer-Utils.fs"
                @"Viewer.fs"
                @"RemoteControlModel.fs"
                @"RemoteControlApp.fs"
                @"Program.fs"
            ]

    let sw = System.Diagnostics.Stopwatch.StartNew()
    let res = Async.RunSynchronously run
    sw.Stop()

    printfn "took: %.3fs" sw.Elapsed.TotalSeconds

    System.GC.Collect()
    System.GC.WaitForFullGCComplete() |> ignore
    Console.ReadLine() |> ignore
    
    System.GC.Collect()
    System.GC.WaitForFullGCComplete() |> ignore
    Console.ReadLine() |> ignore

    printfn "RESULT: %A" res
    0 // return an integer exit code
